name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install mkdocs-material pyyaml

      # --- DEV ---
      - name: Generate DEV nav
        run: python scripts/generate_nav.py dev

      - name: Build DEV
        run: mkdocs build --site-dir site/dev

      # --- TEST ---
      - name: Generate TEST nav
        run: python scripts/generate_nav.py test

      - name: Build TEST
        run: mkdocs build --site-dir site/test

      # --- PROD ---
      - name: Generate PROD nav
        run: python scripts/generate_nav.py prod

      - name: Build PROD
        run: mkdocs build --site-dir site/prod

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          publish_dir: ./site
